
Aplauso.destroy_all
Dinamica.destroy_all
Juego.destroy_all

# Aplausos ###########################
Aplauso.create(nombre: "Aplauso del amor", descripcion: "Es una canción con gestos con las manos.\nTilín tilón, osito regalón\nTilín tilón, te doy mi corazón (con las manos se forma un corazón y se lanza como si entregara amor a alguien)")
Aplauso.create(nombre: "Aplauso locomotora", descripcion: "Los participantes se ponen en círculo y comienzan a frotar sus palmas lentamente simulando el sonido de una locomotora cuando comienza a andar.\n\n\n")
Aplauso.create(nombre: "Aplauso del estadio", descripcion: "Se debe dividir a los participantes en diferentes secciones que representan a diferentes zonas del estadio.\n\n\n")
Aplauso.create(nombre: "Hoja de té té", descripcion: "Se debe cantar la canción al ritmo de los aplausos\nHoja de té, de té, de té.\nHoja de té, de té, de té.\nHoja de té, hoja de té, té.\nLuego se repite el ritmo con las palmas pero sin cantar la canción, solamente con el ritmo\n\n\n")
Aplauso.create(nombre: "Aplauso lluvia", descripcion: "Cada persona comienza el aplauso golpeando un dedo con su palma simulando el comienzo de la lluvia, mientras va avanzando van agregando más dedos fingiendo que la lluvia aumenta. Luego se aplaude con las 2 palmas simulando lluvia muy fuerte. Finalmente, comienzan de a poco a quitar los dedos del aplauso para simular que se termina de llover.\n\n\n")


Aplauso.create(nombre: "Aplauso Bandana", descripcion: "Quien lidera el aplauso tira una bandana al aire y mientras se encuentra fuera de las manos del monitor los participantes deben aplaudir. Cuando el líder del juego vuelve a tomar la bandana con las manos los participantes dejan de aplaudir.")

Aplauso.create(nombre: "Aplauso de Torero", descripcion: "En este aplauso se debe repetir al ritmo la siguiente frase: 'Para pa pa… olé'. En el 'para pa pa' se aplaude y en el 'olé' se hace un gesto de torero.")

Aplauso.create(nombre: "Aplauso Pie Mano", descripcion: "En este aplauso primero hay que dar un pisotón con el pie derecho, después aplaudir una vez, luego dar un pisotón con el pie izquierdo, aplaudir dos veces y finalmente dar dos pisotones con ambos pies.")

Aplauso.create(nombre: "Aplauso Dominó", descripcion: "Todos los integrantes tienen que estar agachados con las rodillas en el piso en una fila, de modo que el primero cuando se cae aplaude y hace caer al segundo que aplaude cuando cae, este al tercero que también aplaude y así sucesivamente hasta que todos caen y aplauden.")

# Creación del aplauso "Alcancía"
Aplauso.create(nombre: "Alcancía", descripcion: "Todos los participantes se ponen en círculo y el moderador crea una historia relacionada a una alcancía, en esta se deben ir poniendo monedas. El moderador avanza a través del círculo y los participantes aplauden simulando que caen monedas en la alcancía mientras va pasando. Objetivo: Fomentar la creatividad y la participación grupal.")

# Creación del aplauso "Loco Adams"
Aplauso.create(nombre: "Loco Adams", descripcion: "Este aplauso imita la canción original de los Locos Adams y busca seguir con el ritmo de las palmas el siguiente ritmo: Para pa pa pa pa / Para pa pa pa pa / Para pa pa Para pa pa / Para pa pa pa pa. Objetivo: Divertirse y coordinar el ritmo de las palmas.")

# Creación del aplauso "Rompe Hielo Simple"
Aplauso.create(nombre: "Rompe Hielo Simple (del primer día)", descripcion: "Este aplauso simple sirve para romper el hielo entre gente que no se conoce y tiene vergüenza de interactuar. El líder del aplauso separa en grupos a los participantes y los grupos deben seguir al líder en su turno, buscando actuar en perfecta sincronización. Primera orden: Aplauso!!, Segunda orden: Aplauso!! Aplauso!!, Última orden: Aplauso!! Aplauso!! y decir: uuuuuUUUUUuuuuuuHHHH!!!!! (con levantamiento y bajada de brazos). Repetir varias veces hasta que el uuuuuu!! se escuche fuerte y animado. Objetivo: Promover la interacción social y crear un ambiente animado y divertido.")

# Creación del aplauso "Resbalín"
Aplauso.create(nombre: "Resbalín", descripcion: "En este aplauso se debe estirar un brazo hacia adelante y luego pasar la mano contraria por el antebrazo y después se debe aplaudir, esto para simular el paso por un resbalín. Objetivo: Fomentar la coordinación y la creatividad en el aplauso.")

# Creación del aplauso "Choco Choco La La"
Aplauso.create(nombre: "Choco Choco La La", descripcion: "Se ponen en parejas y frente a frente los participantes y cantan mientras hacen choque de manos la siguiente canción: Choco choco la la / Choco choco te te / Choco la / Choco te / Choco la te. En el “Choco” se hace palma con palma. En el “la” se hace con la parte trasera de la mano y en el “te” con la mano empuñada. Objetivo: Fomentar la coordinación y la diversión entre los participantes.")


# Juego ###########################
Juego.create(nombre: "El portal dimensional", descripcion: "Es un juego grupal para 10 o más participantes de 10 a 40 años, diseñado para jugarse en una cancha. Los jugadores se dividen en dos equipos de investigadores atrapados en el pasado, que deben resolver enigmas y desafíos para obtener 9 llaves y regresar al presente a través de un portal. Cada jugador entra al portal uno a la vez para intentar resolver un enigma. Si falla, regresa a su equipo y otro miembro puede intentarlo. El equipo que desbloquee todas las llaves primero, gana. \n\n Objetivos: El juego fomenta el trabajo en equipo, la comunicación y la resolución de problemas, y tiene variantes para aumentar el desafío y la diversión.")
Juego.create(nombre: "1,2,3 Bomba", descripcion: "Es un juego funcional para 5 a 15 participantes de 8 años en adelante. Los jugadores forman un círculo y uno se coloca en el centro, hincado y contando en silencio hasta 30, levantando progresivamente partes de su cuerpo. Mientras tanto, los demás pasan un balón de mano en mano hacia la derecha. Cuando el jugador central grita ¡Bomba!, el jugador que tenga el balón queda eliminado. El último jugador en el círculo gana. Con reglas adicionales para grandes grupos y variaciones como agregar un segundo balón, el juego mantiene a los participantes alertas y activos. \n\nObjetivos: Desarrollar la agilidad, coordinación motora, rapidez de reacción y fomentar la atención y concentración.")
Juego.create(nombre: "Charadas (la olla)", descripcion: " Es un juego en equipo para 20 a 40 participantes de 10 a 80 años, ideal para jugar en un espacio amplio. Los jugadores se dividen en dos equipos y toman turnos para actuar palabras o frases escritas en papeles, seleccionados al azar de una bolsa. Sin hablar ni hacer sonidos, los actores interpretan las palabras mientras sus equipos intentan adivinarlas en un tiempo de 3 a 5 minutos por ronda. El equipo que adivina más palabras gana. El juego fomenta el trabajo en equipo, la creatividad y la expresión corporal, con variantes como competir simultáneamente o crear las propias frases para añadir diversión. \n\nObjetivos:Trabajo en equipo, creatividad, expresión corporal.")
Juego.create(nombre: "En el bosque", descripcion: "Descripción: Es un juego grupal de velocidad y estrategia donde un jugador actúa como el Lobo y los demás como Niños. Los niños forman un círculo y cantan una canción mientras el lobo responde con frases como Estoy durmiendo o Me estoy cambiando. En la cuarta ronda, el lobo grita ¡Voy por ustedes! y trata de atrapar a los niños usando sus garras. Si el lobo atrapa a todos los niños en menos de tres minutos, gana; de lo contrario, los niños ganan. Una variante incluye un Cazador que intenta atrapar al lobo usando un aro.")
Juego.create(nombre: "Las quemadas", descripcion: " Las quemadas es un juego de equipo en el que participan de 8 a 30 jugadores, dividido en dos equipos. Cada equipo ocupa un cuadrado de los dos de la cancha y su objetivo es quemar a los oponentes lanzándoles una pelota que debe golpear su cuerpo y caer al suelo. Si la pelota golpea la cabeza o es atrapada con las manos, no cuenta como quemada. Un capitán comienza en el cementerio, la zona externa al cuadrado del oponente, y puede atrapar pelotas y pasarlas a sus compañeros o intentar quemar a los oponentes. Los jugadores quemados se trasladan al cementerio para seguir jugando desde allí. El juego termina cuando un equipo se queda sin jugadores en su cuadrado. \n\nObjetivos: Fomentar la actividad física y la coordinación motora, desarrollar el trabajo en equipo y la estrategia, mejorar las habilidades de lanzamiento y recepción y promover la comunicación y colaboración entre los jugadores.")
Juego.create(nombre: "La Granja Encantada", descripcion: "La Granja Encantada es un juego grupal para 5 a 40 participantes, ideal para edades entre 9 y 40 años, que se juega en una cancha. Los jugadores asumen tres roles: el mago, los campesinos y los espantapájaros. Los campesinos deben cruzar la cancha sin ser tocados por el mago, quien permanece en una zona central delimitada. Si un campesino es tocado por el mago, se convierte en espantapájaros, debiendo permanecer inmóvil y con los brazos extendidos para atrapar a otros campesinos y convertirlos también en espantapájaros. El juego termina cuando solo queda un campesino sin ser tocado, quien es declarado ganador.\n\n\nObjetivos: Fomentar la velocidad y la resistencia física, desarrollar la destreza y la agilidad, promover la estrategia y el pensamiento táctico, potenciar la coordinación y reflejos.")
Juego.create(nombre: "Paises", descripcion: "Es un juego grupal diseñado para entre 5 y 30 participantes de edades entre 7 y 40 años, idealmente jugado en una cancha. Los jugadores eligen cada uno un país y se posicionan en círculo. Comienza cuando se lanza una pelota al aire y se grita el nombre de otro país. Los jugadores deben correr lo más lejos posible mientras el país nombrado intenta atrapar la pelota antes de que toque el suelo. Si tiene éxito, nombra otro país y el juego continúa. Si no, grita 'stop' y da tres pasos hacia el jugador más cercano para lanzarle la pelota con cuidado y eliminar una vida. El juego termina cuando queda un solo país. Hay variantes como saltar en lugar de correr o esquivar la pelota como 'gelatina' al gritar 'stop'. Si hay muchos jugadores, se puede jugar en parejas sin soltarse de las manos.")

Juego.create(nombre: "Salvando a mi compañere", descripcion: "Es un juego grupal para personas de 13 a 50 años, idealmente realizado en una cancha de pasto sintético con un mínimo de 8 participantes. No requiere materiales y simula la situación de trasladar a compañeros desmayados a un centro asistencial en diferentes niveles de dificultad acordados por el grupo. Los jugadores deben emplear fuerza, resistencia y coordinación para llevar a cabo los traslados usando técnicas como arrastrar por las manos, cargar por la espalda, o trasladar por manos y piernas. No se trata de una competencia, sino de cooperación y cuidado mutuo, con variantes para adaptar la dificultad según las capacidades del grupo.")

Juego.create(nombre: "Captura la bandera", descripcion: "es un juego de estrategia y acción al aire libre, donde dos equipos compiten para capturar la bandera del oponente y llevarla a su base. El campo se divide en dos zonas; cada equipo defiende su bandera mientras intenta capturar la del adversario. Los jugadores capturados en territorio enemigo son llevados a prisión y pueden ser liberados por compañeros. La estrategia incluye defensa, ataque y distracción. El juego termina cuando un equipo logra capturar y regresar la bandera rival sin ser capturado, promoviendo trabajo en equipo y actividad física. /n Objetivos: Velocidad, resistencia, estrategia")

Juego.create(nombre: "Guerra de canciones", descripcion: "Es un juego grupal para entre 15 y 40 participantes de edades entre 9 y 40 años, ideal para un espacio plano donde formar un círculo con los jugadores. Se dividen en grupos y cada uno recibe un tema anunciado por el moderador, como amor, animales o verano. Los grupos deben pensar rápidamente en canciones relacionadas con ese tema y cantarlas por turnos cuando sean señalados. Las reglas incluyen cantar correctamente, no repetir canciones y todos los miembros participar activamente. Los grupos pierden si no cantan a tiempo, omiten participación o no conocen la letra. El juego continúa hasta que quede un grupo o se decida un ganador por votación del público o del moderador.")

Juego.create(nombre: "Among Us", descripcion: "Es un juego grupal simbólico para al menos 20 participantes de 10 años en adelante, idealmente en un espacio amplio. Se dividen en tres roles: ciudadanos que deben descubrir a los impostores, impostores que eliminan ciudadanos con un apretón de manos fuerte, y espías fantasmas que ayudan a los ciudadanos una vez eliminados. Los ciudadanos acusan a los impostores en reuniones de emergencia; si la mayoría está de acuerdo, el acusado revela su rol. Los impostores ganan si eliminan a 2/3 de los ciudadanos sin ser descubiertos, mientras que los ciudadanos ganan si eliminan a todos los impostores.")

Juego.create(nombre: "La misión de los conejos", descripcion: "Es un juego colectivo para al menos 8 participantes a partir de los 8 años, ideal en un espacio al aire libre como una cancha. Los jugadores se dividen en equipos que compiten por llevar la mayor cantidad de 'zanahorias' (pelotas de ping pong) a su 'madriguera' (un recipiente). Cada equipo forma una hilera y los participantes deben pasar las pelotas de un vaso a otro mientras saltan de diversas maneras (un pie, dos pies, en parejas). El equipo que logre trasladar tres o más pelotas correctamente al recipiente gana.")

Juego.create(nombre: "Carrera de palabras", descripcion: "Es un juego grupal donde dos equipos equitativos compiten en una cancha. Cada equipo forma una fila en un extremo y, al inicio, el primer participante de cada equipo corre hacia el centro donde están las tarjetas con palabras. Después de elegir una tarjeta, debe decir una oración coherente con esa palabra y regresar corriendo para tocar al siguiente compañero en la fila. El objetivo es completar la carrera con todas las tarjetas primero. El juego fomenta la creatividad, rapidez mental, comunicación verbal y trabajo en equipo.")

Juego.create(nombre: "Relojito", descripcion: "Es un juego grupal que se desarrolla en una cancha de pasto sintético y está diseñado para grupos de 6 a 12 personas de todas las edades, con un total de 35 participantes. Los jugadores se dividen en grupos numerados del 1 al 12, adaptando los números si hay menos participantes. Forman un círculo sentados en el suelo, con un pañolín en el centro. A través de instrucciones narradas por el animador, como galopar, pegarse en diversas partes del cuerpo para simular obstáculos y realizar acciones como giros y saltos, los equipos compiten siguiendo las indicaciones. Variaciones incluyen formas diferentes de moverse alrededor del círculo.")

Juego.create(nombre: "Casa inquilino", descripcion: "Es un juego de grupo donde los participantes se dividen en parejas, uno siendo la 'casa' y el otro el 'inquilino'. El objetivo es que los inquilinos corran y busquen una casa para 'vivir' tocándola o entrando en un área designada. Después de un tiempo determinado, algún integrante que quede solo puede gritar 'terremoto' (todos se desarman y buscan casas e inquilinos) o 'inquilino' (solo cambian los inquilinos), lo mismo si gritan casa, entonces consiste en que los roles se intercambian.")

Juego.create(nombre: "Cachipun actuado león cazador escopeta", descripcion: "Es una versión dinámica del clásico piedra, papel, tijera. Se juega entre dos equipos. Durante una cuenta regresiva o ritmo marcado, ambos equipos actúan como leones rugiendo, cazadores con brazo al pecho y escopetas disparando. Al detenerse el ritmo, cada equipo debe adivinar y actuar en respuesta a la interpretación del otro equipo para eliminarlos según las reglas establecidas (león vence a cazador, cazador vence a escopeta, escopeta vence a león). El objetivo es eliminar a todos los jugadores del equipo contrario para ganar la ronda, haciendo del juego una competencia divertida y llena de energía.")

Juego.create(nombre: "Pinta pareja", descripcion: "Los participantes forman parejas y se colocan en círculo junto con otras parejas. Una pareja es designada como la 'pinta pareja' y debe perseguir a las demás mientras las otras parejas corren, las parejas quemadas deben quedarse inmóviles (las pueden despintar o salir del juego dependiendo de la variante) o también, si la pareja original logra pintar a otros, esa pareja se convierte en la nueva 'pinta pareja' y el juego continúa.")

Juego.create(nombre: "Suma loca", descripcion: "Suma Loca es un juego competitivo para varios equipos de 10 personas cada uno, en el que se utilizan papeles gigantes con números del 0 al 9. Un mediador se sitúa en la mitad de la cancha y plantea una operación matemática (suma, resta, multiplicación o división). Los equipos deben formar rápidamente la respuesta correcta utilizando los números que tienen. El primer equipo en llegar a la mitad de la cancha y organizarse en fila para mostrar la respuesta correcta gana un punto. Terminará el juego cuando un equipo llegue a cierta cantidad de puntos.")

Juego.create(nombre: "El mesero", descripcion: "Consiste en un juego al aire libre diseñado para grupos de al menos 10 personas. Cada equipo simula ser meseros en un restaurante. Cada equipo se forma en hilera en un extremo de la cancha y compiten para llevar una bandeja con una botella de agua desde el extremo hasta la mitad de una cancha y regresar, sin que la botella se caiga. Los participantes deben pasar la bandeja a través de varios integrantes de su equipo, y el equipo más rápido en completar el recorrido gana.")

#news
Juego.create(nombre: "La Misión de la Torre Tallarín", descripcion: "Consiste en un juego grupal en el que los participantes, organizados en equipos de al menos 10 personas, compiten para construir la torre más alta posible utilizando tallarines y malvaviscos. Cada equipo tiene 5 minutos para construir su torre, que debe permanecer en pie durante al menos 10 segundos para ser considerada válida. El equipo con la torre más alta y estable, que haya colocado un malvavisco en la cima, gana la competencia. Requiere habilidad manual, precisión y coordinación entre los jugadores, generando diversión y risas cuando la torre se tambalea o cae. Es una actividad que fomenta el trabajo en equipo y el espíritu competitivo en un ambiente divertido y social.")

Juego.create(nombre: "El Aguatero", descripcion: "Consiste en un juego grupal y funcional adecuado para espacios abiertos o cerrados. Los participantes, organizados en equipos de al menos 8 personas, asumen el rol de repartidores de agua. Cada equipo debe transportar botellas de agua desde una línea de partida hasta un objetivo en la mitad de la cancha, utilizando una liga con cuerdas atadas a esta. Los jugadores no pueden usar las manos para mover las botellas; deben trabajar juntos para levantar y mover cada botella con las ligas. El primer equipo en completar la tarea sin dejar caer las botellas gana. Fomenta el trabajo en equipo y la colaboración, desarrolla rapidez y agilidad en los participantes, mejora el equilibrio y la coordinación, y estimula la comunicación efectiva y la estrategia.")

Juego.create(nombre: "Detective Burbuja", descripcion: "Consiste en que los jugadores se organizan en un círculo cerrado con las manos en las espaldas, excepto uno que asume el papel de detective y se pondrá en el centro del círculo. Los jugadores representan los habitantes de un pueblo ficticio llamado Pueblo Burbuja, entre estos hay un frasco de burbujas, que está en las manos de algún jugador. El detective, con los ojos cerrados inicialmente, debe identificar quién entre los habitantes tiene el frasco en un momento dado. Mientras tanto, los habitantes intentan soplar burbujas sin ser descubiertos, utilizando estrategias como pasar el frasco entre ellos o soplar disimuladamente. El detective tiene tres oportunidades para señalar al sospechoso correcto antes de que los habitantes completen su objetivo de soplar burbujas un determinado número de veces. Promueve el trabajo en equipo al coordinar tácticas para despistar al detective y mantener oculto el frasco de burbujas. Para el detective se desarrollan habilidades de percepción y atención, quien debe confiar en pistas visuales y auditivas para identificar al portador del frasco.")





# Dinámicas ###########################


Dinamica.create(nombre: "Larai lai lero", descripcion: "Consiste en una canción corta e interactiva que combina movimientos y canto. La canción es la siguiente: Larai lai lero, larai lai lero, larai lai lero lero lero lai. Los movimientos son: Palmadas en las rodillas cuando se dice “larai”, aplauso cuando se dice “lai” y mano izquierda en oreja derecha y mano derecha en nariz o viceversa cuando se dice “lero”.")

Dinamica.create(nombre: "El Arca de Noé", descripcion: "Consiste en una canción interactiva que combina movimiento y canto para representar la historia de Noé y su arca. Guiados por un líder, los participantes imitan los movimientos específicos que corresponden a Noé y cada animal mencionado en la canción. La canción es la siguiente: 'Un día Noé, en su arca partió, y muchos animales, de 2 en 2 subió. Al son del cocodrilo y el orangután, la pícara serpiente y el águila real. El conejo, el topo y el elefante loco, loco, loco, sumamente loco'. Los movimientos incluyen: peinarse la barba larga de Noé, mecer un arca con los brazos, simular caminar como cocodrilo, rascar axilas como orangután, simular serpiente con manos juntas, volar como águila, orejas de conejo, manos a la nariz como topo y brazo como trompa de elefante.")

Dinamica.create(nombre: "El Noble Duque Juan", descripcion: "Consiste en una canción interactiva que combina movimiento y canto. Guiados por un líder, los participantes imitan los movimientos específicos mientras repiten la canción. La canción es la siguiente: 'El noble duque Juan tenía hombres mil, subía la montaña y bajaba otra vez. Cuando sube sube sube, cuando baja, baja, baja. Y en el medio del camino subo subo y bajo yo'. Los movimientos incluyen: partir medio agachados al empezar la canción, subir de a poco los brazos y el cuerpo cuando se dice palabras relacionadas con 'subir', y empezar a agacharse de a poco y bajar los brazos cuando se dice palabras relacionadas con 'bajar'.")

Dinamica.create(nombre: "Aiepo", descripcion: "Consiste en una versión alternativa de la canción de percusión corporal llamada 'Epo e Tai Tai e'. Guiados por un líder, los participantes imitan los movimientos específicos mientras repiten la canción. La canción es la siguiente: 'Aiepo i tai tai epo, i tuki tuki epo, i tuki tuki e e po'. Los movimientos incluyen: palmadas en ambas piernas con ambas manos cuando se dice 'epo', aplausos cuando se dice 'tai' y palmadas en la cabeza cuando se dice 'tuki'.")


Dinamica.create(nombre: "El cuerpo relajado", descripcion: "El líder dirige y todos repiten:\n'El cuerpo relajado, relajado, relajado, El cuerpo relajado, así, así, así.'\nLuego, se canta y se relaja cada parte del cuerpo, por ejemplo:\n'Las manos relajadas, relajadas, relajadas, Las manos relajadas, así, así, así.'\nEsto se repite con los brazos, hombros, cuello, cabeza, etc., promoviendo la relajación total.\n\n\nObjetivo: Promover la relajación total del cuerpo a través de la repetición y la canción.")
Dinamica.create(nombre: "Hula Hula", descripcion: "Consiste en hacer un círculo y colocar un hula hula entremedio de 2 alumnos y estos tienen que lograr pasar el hula hula por todo el círculo mientras están tomados de las manos.\n\n\nObjetivo: Fomentar la coordinación y el trabajo en equipo.")
Dinamica.create(nombre: "Tengo un palo", descripcion: "Es una dinámica de repetición y memoria. Los participantes forman un círculo y un líder comienza cantando 'Tengo un palo, así un palo'. En cada verso, se añade un nuevo elemento, y todos deben repetir los elementos en orden acumulativo. Por ejemplo, 'Ese palo tiene un dedo', 'Ese dedo tiene una uña', y así sucesivamente, añadiendo 'una mancha', 'un color', 'una sombra', etc. El objetivo es recordar y repetir todos los elementos en orden, fomentando la memoria y la capacidad de repetición.\n\n\nObjetivo: Fomentar la memoria y la capacidad de repetición.")



Dinamica.create(nombre: "Yo Corro", descripcion: "El moderador guía a los participantes diciendo frases como '¿qué veo? Un lago, no puedo pasar por aquí, no puedo pasar por allá, entonces paso por el medio' y se golpea una parte del cuerpo. Luego dice '¿qué veo? Un puente, no puedo pasar por aquí, no puedo pasar por allá, entonces paso por el medio' y se golpea otra parte del cuerpo. Los participantes deben seguir los movimientos y las indicaciones del moderador, imitando los golpes en las mismas partes del cuerpo. El juego continúa con el moderador añadiendo más elementos como 'Un túnel', 'Un bosque', y así sucesivamente, cada uno con su propio conjunto de golpes o movimientos.")

Dinamica.create(nombre: "A Moler Café", descripcion: "Es una dinámica en la que los participantes forman un círculo y siguen los movimientos del moderador al ritmo de la canción 'A moler café, a moler café, aaaaaa moler a moler café.' Saltando con el ritmo del cántico hacia el lado que estime el moderador. El moderador puede variar la velocidad y la intensidad de los movimientos para mantener la diversión.")

Dinamica.create(nombre: "El Pistón", descripcion: "En esta dinámica, el moderador dice 'Essss el pistón el que hace andar a la máquina, esss el pistón que hace andar al motor' y cada vez que dice 'motor', los participantes tienen que subir o bajar de manera intercalada. Se repite varias veces con más velocidad para aumentar la dificultad y la diversión.")

Dinamica.create(nombre: "Patos Pollos y Gallinas", descripcion: "El moderador hace un cántico que dice 'Patos pollos y gallinas van corriendo por el gallinero están, perseguidos bárbaramente, por quien? por el patrooonnn, por el patrónnnn' cada parte de la canción tiene una mímica asociada y a medida que se repite el cántico vamos muteando partes y solo haciendo la mímica para mantener la diversión y la agilidad mental de los participantes.")

Dinamica.create(nombre: "Adrenalina", descripcion: "En esta dinámica, el moderador repite el cántico '¿Por qué me gusta la adrenalina?, ¿por qué? no sé' las veces que crea pertinentes, mientras los participantes hacen acciones que pueden incluir saltar, correr en el lugar, hacer gestos exagerados o cualquier otro movimiento físico que implique energía y diversión.")

Dinamica.create(nombre: "A Ram Sam Sam", descripcion: "Consiste en una canción interactiva que combina movimiento y canto. Guiados por un líder, los participantes imitan los movimientos específicos mientras repiten la canción. La canción es la siguiente: A ram zam zam, a ram zam zam, guli guli guli guli guli, a ram zam zam, a rafiq a rafiq, guli guli guli guli guli,a ram zam zam,a rafiq a rafiq, guli guli guli guli guli,a ram zam zam. Los movimientos son: Palmadas en las piernas cuando se dice 'a ram zam zam', giras tus manos como si fueran una rueda adelante de tu pecho cuando se dice 'guli guli guli guli guli' y simulas dormir con palmas juntas cerca de tu cabeza cuando se dice 'a rafiq a rafiq'.")
