
# Creación del juego "Policías y ladrones"
Juego.create(
  nombre: "Policías y ladrones", 
  descripcion: "Este juego es un clásico juego de persecución en el que los jugadores se dividen en dos grupos: policías y ladrones. Este juego necesita de un espacio grande donde se pueda correr, como una cancha. Los ladrones deben correr y esconderse, mientras que los policías intentan atraparlos. Si un ladrón es tocado por un policía, cuenta como atrapado y este tendrá que dejarse llevar hacia una cárcel designada. Los ladrones tendrán una oportunidad para liberar a sus compañeros tocando una pared o cosa específica, donde al hacerlo, se liberan a todos los ladrones dentro de la cárcel. El juego continúa hasta que todos los ladrones hayan sido atrapados o hasta que se acabe el tiempo. Objetivos: Fomentar el trabajo en equipo entre los policías para coordinar la captura de los ladrones, desarrollar la agilidad y la resistencia física al correr y esquivar de los ladrones y mejorar la estrategia y la toma de decisiones rápidas tanto para los policías como para los ladrones."
)

# Creación del juego "La orden del Vikingo"
Juego.create(
  nombre: "La orden del Vikingo", 
  descripcion: "Los jugadores forman un círculo y se les asigna un número en orden, de tal manera que cada jugador tenga a su antecesor numérico a un lado y a su sucesor numérico al otro lado. Exceptuando la persona con el número 1, cuyo antecesor será la persona con el último número, y la persona con el último número tendrá a la persona con el número 1 como antecesor. El juego comienza con alguien tomando el rol de líder vikingo, simulando tener un casco con cuernos usando sus manos. Las personas a su lado derecho e izquierdo deben simular remar hacia el lado correspondiente (derecho si están a su derecha y viceversa). Después de remar, el líder vikingo designa a otro líder aleatoriamente diciendo, por ejemplo, 'ahora el líder vikingo es el 6'. Entonces, la persona con ese número simula el casco y las personas a sus lados empiezan a remar. Cada vez que alguien se equivoca en el movimiento (simulando el casco o remando en la dirección incorrecta), las tres personas involucradas pierden y salen del círculo, que se hace más pequeño. El juego termina cuando queden tres personas o se acabe el tiempo. Objetivos: Fomentar la atención y concentración para seguir correctamente las instrucciones y movimientos, desarrollar la coordinación y la capacidad de respuesta rápida a los cambios de líder, promover la interacción y el trabajo en equipo, ya que todos deben estar atentos a las acciones de los demás, mejorar la memoria y la secuencia numérica al recordar los números y las posiciones de los otros jugadores."
)

# Creación del juego "Cachipún Alemán"
Juego.create(
  nombre: "Cachipún Alemán", 
  descripcion: "Consiste en una versión grupal y dinámica del clásico juego de piedra, papel o tijera (también conocido como 'cachipún'). Los jugadores forman dos hileras, situadas a cierta distancia una de otra. Una persona de cada hilera tendrá que hacer un recorrido en forma invertida de letra 'U' (en cada punta hay una hilera), de tal manera que se topen con el oponente. Cuando se encuentran tienen que jugar una ronda de cachipún (piedra, papel o tijera). El jugador que gana la ronda continúa avanzando hacia la línea de partida del equipo contrario, mientras que el jugador que pierde regresa al final de su fila, y el siguiente jugador de su equipo avanza para encontrarse con el ganador anterior. El objetivo es que un jugador logre llegar a la línea de partida del equipo contrario para ganar. Objetivos: Fomentar la rapidez mental y la toma de decisiones rápidas, promover el trabajo en equipo y la coordinación, ya que los jugadores deben estar listos para enfrentarse rápidamente y adaptarse a las situaciones, mejorar la interacción social y la competencia amistosa entre los participantes, desarrollar habilidades motoras y de movimiento, ya que los jugadores deben avanzar rápidamente hacia el centro y luego hacia la línea de meta."
)

# Creación del juego "Perro, Gato y Ratón"
Juego.create(
  nombre: "Perro, Gato y Ratón", 
  descripcion: "Los participantes se dividen en tres grupos con igual cantidad de personas, formando círculos tomados de las manos y mirando hacia el centro. Un grupo representa a los ratones, otro a los perros y otro a los gatos. Cada grupo elige un representante que se coloca en el centro del círculo. La meta del juego es que los representantes salgan del círculo, persigan y toquen a otros jugadores dependiendo del animal que representan, el perro persigue al gato, el gato al ratón y el ratón al perro. El primero en tocar a su objetivo gana la ronda. Los representantes no pueden ser atrapados mientras estén dentro de su círculo, pero tienen un límite de tiempo para permanecer allí. El representante que es tocado y que determina el término de la ronda, se convierte en parte del círculo del representante que lo tocó. Objetivos: Fomentar la rapidez y agilidad física, promover el trabajo en equipo y la coordinación grupal, desarrollar habilidades de estrategia y planificación, mejorar la interacción social y la competencia amistosa."
)


Aplauso.create(nombre: "Aplauso de la carrera de caballos", descripcion: "Es una carrera de caballos, todos los participantes deben estar dándose golpes en las piernas simulando un galope. El moderador narra la carrera con diferentes instrucciones en el orden que estime conveniente. Las instrucciones pueden ser: Pasa por el agua: pegarse en las mejillas, Pasa por el túnel: pegarse en el pecho, Pasa por el pasto: se frotan las manos, Gira a la derecha: se inclinan a la derecha, Gira a la izquierda: se inclinan a la izquierda, Salto/doble Salto: levantan los brazos, Llega a la meta: hacen una pose.")

Aplauso.create(nombre: "Aplauso popeye", descripcion: "Este aplauso imita la canción de 'Popeye' y utiliza las palmas y los muslos. Se canta la siguiente canción: Popeye el marino soy (palmas), (2 aplausos en los muslos), Comiendo espinaca voy (palmas), (2 aplausos en los muslos), Por los siete mares, conquisto a las chicas (palmas), Popeye el marino soy (palmas), (2 aplausos en los muslos). Después se intercambian las palmas por los aplausos en los muslos y vice versa.")

Aplauso.create(nombre: "Boom snap clap", descripcion: "Este aplauso tiene una canción y en cada parte hay que hacer una acción diferente. La canción dice así: Boom, snap, clap, Boom boom, snap, clap, snap, Boom, snap, clap, Boom boom, snap, Shh. En el boom hay que golpear con una mano en el pecho. En el snap hay que chasquear los dedos. En el clap hay que aplaudir y en el shh hay que hacer gesto de silencio con el dedo.")



Dinamica.create(nombre: "La dinámica de la pata", descripcion: "Todos están en círculo y en hilera, cada vez que dicen 'pachi' se avanza un paso con uno de tus pies. La canción es la siguiente: Ahí viene mamá pata (¡Pachi!), Ahí viene papá pato (¡Pachi!), Ahí vienen los patitos (¡Pachi! ¡Pachi! ¡Pachi!), Ten cuidado Pachí, con los patitos no te metai.")
