# Juegos

Aplauso.destroy_all
Dinamica.destroy_all
Juego.destroy_all

# Aplausos
Aplauso.create(nombre: "Aplauso del amor", descripcion: "Es una canción con gestos con las manos.\nTilín tilón, osito regalón\nTilín tilón, te doy mi corazón (con las manos se forma un corazón y se lanza como si entregara amor a alguien)")
Aplauso.create(nombre: "Aplauso locomotora", descripcion: "Los participantes se ponen en círculo y comienzan a frotar sus palmas lentamente simulando el sonido de una locomotora cuando comienza a andar.\n\n\n")
Aplauso.create(nombre: "Aplauso del estadio", descripcion: "Se debe dividir a los participantes en diferentes secciones que representan a diferentes zonas del estadio.\n\n\n")
Aplauso.create(nombre: "Hoja de té té", descripcion: "Se debe cantar la canción al ritmo de los aplausos\nHoja de té, de té, de té.\nHoja de té, de té, de té.\nHoja de té, hoja de té, té.\nLuego se repite el ritmo con las palmas pero sin cantar la canción, solamente con el ritmo\n\n\n")
Aplauso.create(nombre: "El cuerpo relajado", descripcion: "El líder dirige y todos repiten:\n'El cuerpo relajado, relajado, relajado,\nEl cuerpo relajado, así, así, así.'\nLuego, se canta y se relaja cada parte del cuerpo, por ejemplo:\n'Las manos relajadas, relajadas, relajadas,\nLas manos relajadas, así, así, así.'\nEsto se repite con los brazos, hombros, cuello, cabeza, etc., promoviendo la relajación total.\n\n\n")
Aplauso.create(nombre: "Hula Hula", descripcion: "Consiste en hacer un círculo y colocar un hula hula en medio de 2 alumnos y estos tienen que lograr pasar el hula hula por todo el círculo mientras están tomados de las manos.\n\n\n")
Aplauso.create(nombre: "Aplauso lluvia", descripcion: "Cada persona comienza el aplauso golpeando un dedo con su palma simulando el comienzo de la lluvia, mientras va avanzando van agregando más dedos fingiendo que la lluvia aumenta. Luego se aplaude con las 2 palmas simulando lluvia muy fuerte. Finalmente, comienzan de a poco a quitar los dedos del aplauso para simular que se termina de llover.\n\n\n")





# Juego
Juego.create(nombre: "El portal dimensional", descripcion: "Es un juego grupal para 10 o más participantes de 10 a 40 años, diseñado para jugarse en una cancha.\n\n\nObjetivos: Fomenta el trabajo en equipo, la comunicación y la resolución de problemas, y tiene variantes para aumentar el desafío y la diversión.")
Juego.create(nombre: "1,2,3 Bomba", descripcion: "Es un juego funcional para 5 a 15 participantes de 8 años en adelante.\n\n\nObjetivos: Desarrollar la agilidad, coordinación motora, rapidez de reacción y fomentar la atención y concentración.")
Juego.create(nombre: "Charadas (la olla)", descripcion: "Es un juego en equipo para 20 a 40 participantes de 10 a 80 años, ideal para jugar en un espacio amplio.\n\n\nObjetivos: Trabajo en equipo, creatividad, expresión corporal.")
Juego.create(nombre: "Cruzando el río", descripcion: "Es un juego grupal para participantes de 7 años en adelante, diseñado para desarrollarse en una cancha de pasto sintético con un mínimo de 10 personas y sin límite máximo.\n\n\nObjetivos: El juego fomenta la coordinación, el equilibrio, el trabajo en equipo y la comunicación.")
Juego.create(nombre: "En el bosque", descripcion: "Es un juego grupal de velocidad y estrategia donde un jugador actúa como el 'Lobo' y los demás como 'Niños'.\n\n\nObjetivos: Desarrollar estrategias y rapidez en la toma de decisiones, así como fomentar la coordinación y la cooperación en equipo.")
Juego.create(nombre: "Las quemadas", descripcion: "Las quemadas es un juego de equipo en el que participan de 8 a 30 jugadores, dividido en dos equipos.\n\n\nObjetivos: Fomentar la actividad física y la coordinación motora, desarrollar el trabajo en equipo y la estrategia, mejorar las habilidades de lanzamiento y recepción y promover la comunicación y colaboración entre los jugadores.")
Juego.create(nombre: "El Teatro", descripcion: "El Teatro es un juego en el que participan al menos 10 jugadores, sin límite máximo de participantes. Se forman varios grupos, cada uno de los cuales escribe una obra de teatro que otro grupo deberá actuar. Tras recibir las obras de manera aleatoria, cada grupo reparte los roles que tomarán en la obra. Luego, cada equipo presenta su actuación frente a los demás y se califica en función de la fidelidad al guión recibido. El equipo con la mejor calificación en la actuación gana. El juego se desarrolla en etapas, y con antelación se decide el tiempo para escribir, organizarse y actuar.\n\n\nObjetivos: Fomentar la confianza y perder la vergüenza entre los participantes, promover un ambiente positivo y de buen compañerismo, facilitar la creatividad y la expresión artística, mejorar la coordinación y el trabajo en equipo.")
Juego.create(nombre: "La Granja Encantada", descripcion: "La Granja Encantada es un juego grupal para 5 a 40 participantes, ideal para edades entre 9 y 40 años, que se juega en una cancha. Los jugadores asumen tres roles: el mago, los campesinos y los espantapájaros. Los campesinos deben cruzar la cancha sin ser tocados por el mago, quien permanece en una zona central delimitada. Si un campesino es tocado por el mago, se convierte en espantapájaros, debiendo permanecer inmóvil y con los brazos extendidos para atrapar a otros campesinos y convertirlos también en espantapájaros. El juego termina cuando solo queda un campesino sin ser tocado, quien es declarado ganador.\n\n\nObjetivos: Fomentar la velocidad y la resistencia física, desarrollar la destreza y la agilidad, promover la estrategia y el pensamiento táctico, potenciar la coordinación y reflejos.")
Juego.create(nombre: "Paises", descripcion: "Es un juego grupal diseñado para entre 5 y 30 participantes de edades entre 7 y 40 años, idealmente jugado en una cancha. Los jugadores eligen cada uno un país y se posicionan en círculo. Comienza cuando se lanza una pelota al aire y se grita el nombre de otro país. Los jugadores deben correr lo más lejos posible mientras el país nombrado intenta atrapar la pelota antes de que toque el suelo. Si tiene éxito, nombra otro país y el juego continúa. Si no, grita 'stop' y da tres pasos hacia el jugador más cercano para lanzarle la pelota con cuidado y eliminar una vida. El juego termina cuando queda un solo país. Hay variantes como saltar en lugar de correr o esquivar la pelota como 'gelatina' al gritar 'stop'. Si hay muchos jugadores, se puede jugar en parejas sin soltarse de las manos.")

Juego.create(nombre: "Salvando a mi compañere", descripcion: "Es un juego grupal para personas de 13 a 50 años, idealmente realizado en una cancha de pasto sintético con un mínimo de 8 participantes. No requiere materiales y simula la situación de trasladar a compañeros desmayados a un centro asistencial en diferentes niveles de dificultad acordados por el grupo. Los jugadores deben emplear fuerza, resistencia y coordinación para llevar a cabo los traslados usando técnicas como arrastrar por las manos, cargar por la espalda, o trasladar por manos y piernas. No se trata de una competencia, sino de cooperación y cuidado mutuo, con variantes para adaptar la dificultad según las capacidades del grupo.")

Juego.create(nombre: "Captura la bandera", descripcion: "")

Juego.create(nombre: "Guerra de canciones", descripcion: "Es un juego grupal para entre 15 y 40 participantes de edades entre 9 y 40 años, ideal para un espacio plano donde formar un círculo con los jugadores. Se dividen en grupos y cada uno recibe un tema anunciado por el moderador, como amor, animales o verano. Los grupos deben pensar rápidamente en canciones relacionadas con ese tema y cantarlas por turnos cuando sean señalados. Las reglas incluyen cantar correctamente, no repetir canciones y todos los miembros participar activamente. Los grupos pierden si no cantan a tiempo, omiten participación o no conocen la letra. El juego continúa hasta que quede un grupo o se decida un ganador por votación del público o del moderador.")

Juego.create(nombre: "Among Us", descripcion: "Es un juego grupal simbólico para al menos 20 participantes de 10 años en adelante, idealmente en un espacio amplio. Se dividen en tres roles: ciudadanos que deben descubrir a los impostores, impostores que eliminan ciudadanos con un apretón de manos fuerte, y espías fantasmas que ayudan a los ciudadanos una vez eliminados. Los ciudadanos acusan a los impostores en reuniones de emergencia; si la mayoría está de acuerdo, el acusado revela su rol. Los impostores ganan si eliminan a 2/3 de los ciudadanos sin ser descubiertos, mientras que los ciudadanos ganan si eliminan a todos los impostores.")

Juego.create(nombre: "La misión de los conejos", descripcion: "Es un juego colectivo para al menos 8 participantes a partir de los 8 años, ideal en un espacio al aire libre como una cancha. Los jugadores se dividen en equipos que compiten por llevar la mayor cantidad de 'zanahorias' (pelotas de ping pong) a su 'madriguera' (un recipiente). Cada equipo forma una hilera y los participantes deben pasar las pelotas de un vaso a otro mientras saltan de diversas maneras (un pie, dos pies, en parejas). El equipo que logre trasladar tres o más pelotas correctamente al recipiente gana.")

Juego.create(nombre: "Carrera de palabras", descripcion: "Es un juego grupal donde dos equipos equitativos compiten en una cancha. Cada equipo forma una fila en un extremo y, al inicio, el primer participante de cada equipo corre hacia el centro donde están las tarjetas con palabras. Después de elegir una tarjeta, debe decir una oración coherente con esa palabra y regresar corriendo para tocar al siguiente compañero en la fila. El objetivo es completar la carrera con todas las tarjetas primero. El juego fomenta la creatividad, rapidez mental, comunicación verbal y trabajo en equipo.")

Juego.create(nombre: "Relojito", descripcion: "Es un juego grupal que se desarrolla en una cancha de pasto sintético y está diseñado para grupos de 6 a 12 personas de todas las edades, con un total de 35 participantes. Los jugadores se dividen en grupos numerados del 1 al 12, adaptando los números si hay menos participantes. Forman un círculo sentados en el suelo, con un pañolín en el centro. A través de instrucciones narradas por el animador, como galopar, pegarse en diversas partes del cuerpo para simular obstáculos y realizar acciones como giros y saltos, los equipos compiten siguiendo las indicaciones. Variaciones incluyen formas diferentes de moverse alrededor del círculo.")

Juego.create(nombre: "Casa inquilino", descripcion: "Es un juego de grupo donde los participantes se dividen en parejas, uno siendo la 'casa' y el otro el 'inquilino'. El objetivo es que los inquilinos corran y busquen una casa para 'vivir' tocándola o entrando en un área designada. Después de un tiempo determinado, algún integrante que quede solo puede gritar 'terremoto' (todos se desarman y buscan casas e inquilinos) o 'inquilino' (solo cambian los inquilinos), lo mismo si gritan casa, entonces consiste en que los roles se intercambian.")

Juego.create(nombre: "Cachipun actuado león cazador escopeta", descripcion: "Es una versión dinámica del clásico piedra, papel, tijera. Se juega entre dos equipos. Durante una cuenta regresiva o ritmo marcado, ambos equipos actúan como leones rugiendo, cazadores con brazo al pecho y escopetas disparando. Al detenerse el ritmo, cada equipo debe adivinar y actuar en respuesta a la interpretación del otro equipo para eliminarlos según las reglas establecidas (león vence a cazador, cazador vence a escopeta, escopeta vence a león). El objetivo es eliminar a todos los jugadores del equipo contrario para ganar la ronda, haciendo del juego una competencia divertida y llena de energía.")

Juego.create(nombre: "Pinta pareja", descripcion: "Los participantes forman parejas y se colocan en círculo junto con otras parejas. Una pareja es designada como la 'pinta pareja' y debe perseguir a las demás mientras las otras parejas corren, las parejas quemadas deben quedarse inmóviles (las pueden despintar o salir del juego dependiendo de la variante) o también, si la pareja original logra pintar a otros, esa pareja se convierte en la nueva 'pinta pareja' y el juego continúa.")

Juego.create(nombre: "Suma loca", descripcion: "Suma Loca es un juego competitivo para varios equipos de 10 personas cada uno, en el que se utilizan papeles gigantes con números del 0 al 9. Un mediador se sitúa en la mitad de la cancha y plantea una operación matemática (suma, resta, multiplicación o división). Los equipos deben formar rápidamente la respuesta correcta utilizando los números que tienen. El primer equipo en llegar a la mitad de la cancha y organizarse en fila para mostrar la respuesta correcta gana un punto. Terminará el juego cuando un equipo llegue a cierta cantidad de puntos.")

Juego.create(nombre: "El mesero", descripcion: "Consiste en un juego al aire libre diseñado para grupos de al menos 10 personas. Cada equipo simula ser meseros en un restaurante. Cada equipo se forma en hilera en un extremo de la cancha y compiten para llevar una bandeja con una botella de agua desde el extremo hasta la mitad de una cancha y regresar, sin que la botella se caiga. Los participantes deben pasar la bandeja a través de varios integrantes de su equipo, y el equipo más rápido en completar el recorrido gana.")





# Dinámicas
Dinamica.create(nombre: "El cuerpo relajado", descripcion: "El líder dirige y todos repiten:\n'El cuerpo relajado, relajado, relajado, El cuerpo relajado, así, así, así.'\nLuego, se canta y se relaja cada parte del cuerpo, por ejemplo:\n'Las manos relajadas, relajadas, relajadas, Las manos relajadas, así, así, así.'\nEsto se repite con los brazos, hombros, cuello, cabeza, etc., promoviendo la relajación total.\n\n\nObjetivo: Promover la relajación total del cuerpo a través de la repetición y la canción.")
Dinamica.create(nombre: "Hula Hula", descripcion: "Consiste en hacer un círculo y colocar un hula hula entremedio de 2 alumnos y estos tienen que lograr pasar el hula hula por todo el círculo mientras están tomados de las manos.\n\n\nObjetivo: Fomentar la coordinación y el trabajo en equipo.")
Dinamica.create(nombre: "Tengo un palo", descripcion: "Es una dinámica de repetición y memoria. Los participantes forman un círculo y un líder comienza cantando 'Tengo un palo, así un palo'. En cada verso, se añade un nuevo elemento, y todos deben repetir los elementos en orden acumulativo. Por ejemplo, 'Ese palo tiene un dedo', 'Ese dedo tiene una uña', y así sucesivamente, añadiendo 'una mancha', 'un color', 'una sombra', etc. El objetivo es recordar y repetir todos los elementos en orden, fomentando la memoria y la capacidad de repetición.\n\n\nObjetivo: Fomentar la memoria y la capacidad de repetición.")
